### ISSUE TITLE
Hard port to Python 3 for Fedora

### ISSUE THREAD

**Issue by woky** [cgwalters/rpmdistro-gitoverlay#4]
Hello.

Could you please provide instructions on how to build it on Fedora 23?

`rdgo/mockchain.py` uses `mockbuild.util` module, which seems to be in `mock` package but only for Python 3 and I couldn't find a Python 2 version:

```
# rpm -ql mock|grep mockbuild/util
/usr/lib/python3.4/site-packages/mockbuild/util.py
# dnf install /usr/lib/python2.7/site-packages/mockbuild/util.py
No package /usr/lib/python2.7/site-packages/mockbuild/util.py available.
Error: Unable to find a match.
```

When running with Python 3 it fails on:

```
$ rpmdistro-gitoverlay
Traceback (most recent call last):
  File "/home/woky/tmp/rdgo/rdgo-dist/bin/rpmdistro-gitoverlay", line 21, in <module>
    import __builtin__
ImportError: No module named '__builtin__'
```

Thank you.

**Comment by cgwalters** [comment]
Yeah...this is going to be a mess as I'm not quite sure I'm ready to handle dual python2/3 builds =(  I will try to see how much work this at some point, but no guarantees.

Right now I'm primarily using this project myself on Red Hat Enterprise Linux 7 (and CentOS 7).

**Comment by cgwalters** [comment]
I looked at this again...there's really not much of a choice here to match mock's python version =(  The configuation parsing in mock is absolutely insane - it uses `eval`, and there are a lot of config options I don't want to get in the business of duplicating.

**Comment by cgwalters** [comment]
And whee, mock is python3 only, pyrpkg is python 2 only.

**Comment by cgwalters** [comment]
Python 3 was such a $#@$ stupid move...

**Comment by cgwalters** [comment]
This is done in master now.
