### ISSUE TITLE
Proposal: adding rpmbuild options to yaml parsing

### ISSUE THREAD

**Issue by peterbaouoft** [cgwalters/rpmdistro-gitoverlay#44]
Hi, the intention came from https://github.com/openshift/os/pull/11#issuecomment-388369466. There was a build error when trying to build origin package with multiple distributions. To solve that, a workaround is done atm to turn that off. https://github.com/peterbaouoft/rpmdistro-gitoverlay/commit/1242ddc89a0e9e0a693cc732366735267e8d3cd3. But, as you can see, it is very hacky atm(IMO). 

I am thinking of proposing a PR of allowing users to add rpmbuild options in `overlay.yml` so that they can define those build options themselves. Currently, by ~inspections~ observations, it seems we do not allow adding `--rpmbuild-opts` yet to mock build. I want to make a proposal to add that as an option.

Plans for implementation:
1: add an option `buildopts` under each pacakge component. It may be looking like the following:
```
# We also support grabbing a spec file from the upstream git,
  # should they happen to include one.
  - src: github:rpm-software-management/libhif
    spec: internal
    buildopts: 
         variable1: value 
         variable2: value
```
2: Each variable will cause the addition of a `--define` statement in rpmbuild, e.g: `"--define 'make_redistributable 0'"` will be correspondent to
```
   buildopts:
        make_redistributable: 0
```

3: To achieve that, I am thinking adding an extra field of `options` to current SRPM definition. like the current workaround in  https://github.com/peterbaouoft/rpmdistro-gitoverlay/commit/1242ddc89a0e9e0a693cc732366735267e8d3cd3. And then we pass it into the mock commands. 

I am new to this repo tho, so if I happen to have a misunderstanding, please let me know =), and let me know your thoughts on this.

**Comment by cgwalters** [comment]
OK, I'm fine with something like:

```
defines:
   foo: bar
   baz: blah
```

**Comment by peterbaouoft** [comment]
Thanks for the reply :), I am new to this, so I might not know stuff well, hope you don't mind.

> We already support a with flag which controls rpm's e.g. %bcond_with redistributable. But the spec would need to be patched to use it.

Hmm, can you elaborate a bit more? like an example would be greatly helpful :p. 

> OK, I'm fine with something like:

right, that is what I was thinking for first place :).

**Comment by ashcrow** [comment]
@peterbaouoft `%bcond_with` doesn't help us in this situation.

**Comment by peterbaouoft** [comment]
Done in #45, will open a new issue if regression is needed =)
